apiVersion: v1
kind: Service
metadata:
  labels:
    app: kubesphere
    component: django-demo
  name: django-demo
  namespace: django-proj
spec:
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: kubesphere
    component: django-demo
    tier: backend
  sessionAffinity: None
  type: NodePort