apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kubesphere
    component: django-demo
    tier: backend
  name: django-demo
  namespace: django-proj
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  selector:
    matchLabels:
      app: kubesphere
      component: django-demo
      tier: backend
  template:
    metadata:
      labels:
        app: kubesphere
        component: django-demo
        tier: backend
    spec:
      containers:
        - image: registry.cn-huhehaote.aliyuncs.com/ydong/devops-python-sample:18
          imagePullPolicy: Always
          name: ks-sample
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            timeoutSeconds: 10
            failureThreshold: 30
            periodSeconds: 5
          ports:
            - containerPort: 8080
              protocol: TCP
          resources:
            limits:
              cpu: 200m
              memory: 500Mi
            requests:
              cpu: 100m
              memory: 100Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
